//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignCardToBank_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignCardToBank_tbl()
        {
            this.expenses_tbl = new HashSet<expenses_tbl>();
        }
    
        public int ACID { get; set; }
        public Nullable<int> fkpaymodeid { get; set; }
        public Nullable<int> FKbankcardid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
    
        public virtual BankCard BankCard { get; set; }
        public virtual PaymentMode_tbl PaymentMode_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expenses_tbl> expenses_tbl { get; set; }
    }
}
