//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankCard()
        {
            this.AssignCardToBank_tbl = new HashSet<AssignCardToBank_tbl>();
        }
    
        public int Cid { get; set; }
        public string CardName { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignCardToBank_tbl> AssignCardToBank_tbl { get; set; }
    }
}
