//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSEntities8 : DbContext
    {
        public EMSEntities8()
            : base("name=EMSEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category_tbl> category_tbl { get; set; }
        public virtual DbSet<expenses_tbl> expenses_tbl { get; set; }
        public virtual DbSet<sub_category_tbl> sub_category_tbl { get; set; }
        public virtual DbSet<sub_sub_category_tbl> sub_sub_category_tbl { get; set; }
        public virtual DbSet<user_tbl> user_tbl { get; set; }
    }
}
