//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpensesEntities : DbContext
    {
        public ExpensesEntities()
            : base("name=ExpensesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssignCardToBank_tbl> AssignCardToBank_tbl { get; set; }
        public virtual DbSet<BankCard> BankCards { get; set; }
        public virtual DbSet<category_tbl> category_tbl { get; set; }
        public virtual DbSet<expenses_tbl> expenses_tbl { get; set; }
        public virtual DbSet<Monthly_Income_tbl> Monthly_Income_tbl { get; set; }
        public virtual DbSet<PaymentMode_tbl> PaymentMode_tbl { get; set; }
        public virtual DbSet<sub_category_tbl> sub_category_tbl { get; set; }
        public virtual DbSet<sub_sub_category_tbl> sub_sub_category_tbl { get; set; }
        public virtual DbSet<user_tbl> user_tbl { get; set; }
    }
}
