//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sub_category_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sub_category_tbl()
        {
            this.expenses_tbl = new HashSet<expenses_tbl>();
            this.sub_sub_category_tbl = new HashSet<sub_sub_category_tbl>();
        }
        [Display(Name = "Sub-Category Id")] 
        public int subcat_id { get; set; }
        [Display(Name = "Sub-Category Name")]
        public string subcat_name { get; set; }
        [Display(Name = "Created On")]
        public System.DateTime created_on { get; set; }
        [Display(Name = "Created By")]
        public string created_by { get; set; }
        public int fkcat_id { get; set; }
    
        public virtual category_tbl category_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expenses_tbl> expenses_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_sub_category_tbl> sub_sub_category_tbl { get; set; }
    }
}
