//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_category_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sub_category_tbl()
        {
            this.expenses_tbl = new HashSet<expenses_tbl>();
            this.sub_sub_category_tbl = new HashSet<sub_sub_category_tbl>();
            this.user_subcategories_tbl = new HashSet<user_subcategories_tbl>();
            this.user_sub_subcategory_tbl = new HashSet<user_sub_subcategory_tbl>();
        }
    
        public int subcat_id { get; set; }
        public string subcat_name { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
        public int fkcat_id { get; set; }
    
        public virtual category_tbl category_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expenses_tbl> expenses_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_sub_category_tbl> sub_sub_category_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subcategories_tbl> user_subcategories_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_sub_subcategory_tbl> user_sub_subcategory_tbl { get; set; }
    }
}
