//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sub_sub_category_tbl
    {
        [Display(Name = "Sub-Sub-Category Id")]
        public int sub_sub_catId { get; set; }
        [Display(Name = "Sub-Sub-Category Name")]
        public string sub_sub_catName { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<int> fkCatId { get; set; }
        public Nullable<int> fkSubCatId { get; set; }
    
        public virtual category_tbl category_tbl { get; set; }
        public virtual sub_category_tbl sub_category_tbl { get; set; }
    }
}
