//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_sub_subcategory_tbl
    {
        public int user_sub_subcategory_id { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> catId { get; set; }
        public Nullable<int> subcatId { get; set; }
        public Nullable<int> subsubcatId { get; set; }
    
        public virtual category_tbl category_tbl { get; set; }
        public virtual sub_category_tbl sub_category_tbl { get; set; }
        public virtual sub_sub_category_tbl sub_sub_category_tbl { get; set; }
        public virtual user_tbl user_tbl { get; set; }
    }
}
