//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_tbl()
        {
            this.expenses_tbl = new HashSet<expenses_tbl>();
        }

        [Display(Name = "User Id")]
        public int user_id { get; set; }
        [Display(Name = "User Name")]
        public string user_name { get; set; }
        [Display(Name = "Address")]
        public string address { get; set; }
        [Display(Name = "City")]
        public string city { get; set; }
        [Display(Name = "State Name")]
        public string statename { get; set; }
        [Display(Name = "Pincode")]
        public string pincode { get; set; }
        [Display(Name = "Mobile Number")]
        public string mobile_num { get; set; }
        [Display(Name = "Email Id")]
        public string email_id { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expenses_tbl> expenses_tbl { get; set; }
    }
}
