//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_tbl()
        {
            this.expenses_tbl = new HashSet<expenses_tbl>();
            this.Monthly_Income_tbl = new HashSet<Monthly_Income_tbl>();
            this.user_categories_tbl = new HashSet<user_categories_tbl>();
            this.user_subcategories_tbl = new HashSet<user_subcategories_tbl>();
            this.user_sub_subcategory_tbl = new HashSet<user_sub_subcategory_tbl>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string statename { get; set; }
        public string pincode { get; set; }
        public string mobile_num { get; set; }
        public string email_id { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
        public string type { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> OTP_created_on { get; set; }
        public Nullable<System.DateTime> OTP_ends_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expenses_tbl> expenses_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monthly_Income_tbl> Monthly_Income_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_categories_tbl> user_categories_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subcategories_tbl> user_subcategories_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_sub_subcategory_tbl> user_sub_subcategory_tbl { get; set; }
    }
}
